#!/usr/bin/python3
# SPDX-FileCopyrightText: 2026 Riku Terashima
# SPDX-Licence-Indentifier: BSD-3-Clause
import syss

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)



ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
